project:
  base_path: ./
  filters:
    - ignore:
        - target
        - .idea
        - .mvn
        - prompt
        - prompt-builder
        - .git
        - ai_helper
        - node_modules
        - spike
        - dist
        - media
        - "**/.DS_Store"
        - LICENSE.txt
        - package-lock.json
        - .ai_helper
        - example

input:
  prompt_template:
    path: ai_helper/prompt_builder/prompt    
  instruction: |
    # 任务
    我希望 
    - 加一个右键新菜单项，可以把选中文件夹下的所有xml文件的instruction标签的文本内容（含instruction标签本身）提取出来，存储到剪切板里。如果没有就弹出提示没有。
    - 再加一个命令，可以直接读取 .ai_helper/prompt_builder/output/backup 作为目标文件夹来完成同样的功能
  git_clone_to_path: ai_helper/git_repo
  
output:     
  prompt:
    path: .ai_helper/prompt_builder/output/working
    backup_path: .ai_helper/prompt_builder/output/backup
